### PR TITLE
fix: unsound transmutes

### LINKED ISSUE #117: transmuting Vec might lead to undefined behavior
Hello, I've come across these transmutes when browsing the code:

https://github.com/Smithay/drm-rs/blob/e5f5b14d58c0d598cbce4019c706b2b1e0cf7d7e/src/control/mod.rs#L170

https://github.com/Smithay/drm-rs/blob/e5f5b14d58c0d598cbce4019c706b2b1e0cf7d7e/src/control/mod.rs#L539

They are transmuting `Vec<drm_mode_modeinfo>` into `Vec<Mode>`. However, `Vec` has an unspecified layout and this can lead to UB. This is even mentioned in the documentation https://doc.rust-lang.org/std/mem/fn.transmute.html#alternatives (scroll to "Turning a `Vec<&T>` into a `Vec<Option<&T>>`.")

The documentation also offers an alternative:
```rs
let after = unsafe {
    let mut before = std::mem::ManuallyDrop::new(before);
    Vec::from_raw_parts(before.as_mut_ptr() as *mut _, before.len(), before.capacity())
};
```

Secondly, I have also notices these two `Handle` types aren't `repr(transparent)` as they should be. Other `Handle` types are, so I assume this is just an oversight. 

https://github.com/Smithay/drm-rs/blob/e5f5b14d58c0d598cbce4019c706b2b1e0cf7d7e/src/control/encoder.rs#L11

https://github.com/Smithay/drm-rs/blob/e5f5b14d58c0d598cbce4019c706b2b1e0cf7d7e/src/control/crtc.rs#L20

I can open a PR to fix these, should be very simple.

### PR DESCRIPTION
**Pull request by TheEdda**
* missing repr(transparent) on some handles
* transmute of Vec which has unspecified layout

closes #117

### CODE REVIEW

File: src/control/mod.rs [hunk 1]
```diff
@@ -70,6 +70,16 @@ pub fn from_u32<T: ResourceHandle>(raw: u32) -> Option<T> {
     RawResourceHandle::new(raw).map(T::from)
 }
 
+unsafe fn transmute_vec<T, U>(from: Vec<T>) -> Vec<U> {
```
Comment (MarijnS95) [inline src/control/mod.rs:73]: Isn't it more common to use the `safe_transmute` crate for these?

File: src/control/mod.rs [hunk 2]
```diff
@@ -167,7 +177,7 @@ pub trait Device: super::Device {
                 (0, 0) => None,
                 (x, y) => Some((x, y)),
             },
-            modes: unsafe { mem::transmute(modes) },
+            modes: unsafe {  transmute_vec(modes) },
```
Comment (MarijnS95) [inline src/control/mod.rs]:
```suggestion
            modes: unsafe { transmute_vec(modes) },
```

File: src/control/mod.rs (hunk 1 above)
Comment (TheEdda) [reply src/control/mod.rs:73]: I suppose that would warrant converting the whole crate to use such a crate (and/or [getting rid of the transmutes in the first place...](https://github.com/Smithay/drm-rs/issues/117#issuecomment-1159784840)). I assumed since this is very limited in scope and has an explicit example in the std docs I would just implement it right there.

Indeed, it is the same code as some other crates provide, excluding size and alignment checks, which might be a benefit of an existing crate (or it can be added to this function):
* https://docs.rs/transvec/latest/src/transvec/lib.rs.html#511
* https://docs.rs/safe-transmute/latest/src/safe_transmute/full.rs.html#298
* https://docs.rs/bytemuck/latest/src/bytemuck/allocation.rs.html#182

Personally I'm partial to bytemuck as it is most popular, but also the heaviest :woman_shrugging:

Comment (Drakulix) [reply src/control/mod.rs:73]: I think that is out of the scope of this PR. Fixing the currently unsound behaviour should be done first, we can improve upon that later. Feel free to open another issue for discussing the different approaches.

**Review by Drakulix — APPROVED** [review]
LGTM! Thanks
